### ISSUE TITLE
Add a pretty theme as default

### ISSUE THREAD

**Issue by john-pw** [Accenture/adop-jenkins#24]
just a case of adding the simple theme plugin; curling a theme into the $jenkins_home/userContent/. and setting the url string ni the jenkins system config to /userContent/<theme .css>

would also be nice for optional theme for visually impaired users

**Comment by anton-kasperovich** [comment]
As we already have this "Jenkins Simple Theme Plugin" in Jenkins, we just need to find/add a way how to add it on initialization stage, may be something like via "Environment Variables":

```
jenkins:
  container_name: jenkins
  restart: always
  image: accenture/adop-jenkins:0.2.0
  ...
  environment:
    ADOP_PLATFORM_MANAGEMENT_VERSION: "0.1.1"
    JENKINS_SIMPLE_THEME_MATERIAL_CSS: "http://afonsof.com/jenkins-material-theme/dist/material-green.css"
    JENKINS_SIMPLE_THEME_MATERIAL_LOGO: "https://avatars3.githubusercontent.com/u/10454368?v=3&s=200"
```

I think it's can be implemented easily, what do you think guys @nickdgriffin @SachinKSingh28 ?
